Predictor:
  Model:
    classpath: UNetpp:UNetpp5
    UNetpp5:
      outputs_criterions: None
      pretrained: false
  Dataset:
    groups_src:
      MR:
        groups_dest:
          MR:
            transforms: None
            patch_transforms: None
            is_input: true
      MASK:
        groups_dest:
          MASK:
            transforms: None
            patch_transforms: None
            is_input: false
    augmentations:
      DataAugmentation_0:
        data_augmentations:
          Flip:
            f_prob:
            - 0
            - 0
            - 1
            prob: 1
        nb: 1
      DataAugmentation_1:
        data_augmentations:
          Flip:
            f_prob:
            - 0
            - 1
            - 0
            prob: 1
        nb: 1
    Patch:
      patch_size:
      - 1
      - 512
      - 512
      overlap: None
      mask: None
      pad_value: -1
      extend_slice: 4
    subset: None
    filter: None
    dataset_filenames:
    - ./Dataset/AB:a:mha
    use_cache: false
    batch_size: 16
  outputs_dataset:
    Head:Tanh:
      OutputDataset:
        name_class: OutSameAsGroupDataset
        before_reduction_transforms: None
        after_reduction_transforms: None
        final_transforms:
          UnNormalize:UnNormalize: {}
          Mask:
            path: MASK
            value_outside: -1024
          TensorCast:
            dtype: int16
        dataset_filename: Dataset:mha
        group: sCT
        same_as_group: MR:MR
        patch_combine: None
        inverse_transform: false
        reduction: Mean
  train_name: Out
  manual_seed: 32
  gpu_checkpoints: None
  images_log: None
  combine: Mean
  autocast: false
  data_log: None
